AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a backup solution using Lambda and S3.

Parameters:
  SourceBucket:
    Type: String
    Description: The name of the source S3 bucket.
  BackupBucket:
    Type: String
    Description: The name of the backup S3 bucket.

Resources:
  BackupBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BackupBucket

  BackupLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: BackupFunction
      Runtime: python3.8
      Handler: lambda_function.lambda_handler
      Code:
        ZipFile: !Sub |
          import boto3
          import os
          import json
          from datetime import datetime

          s3 = boto3.client('s3')

          def lambda_handler(event, context):
              source_bucket = os.environ['SOURCE_BUCKET']
              backup_bucket = os.environ['BACKUP_BUCKET']
              timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
              response = s3.list_objects_v2(Bucket=source_bucket)

              if 'Contents' not in response:
                  print("No files found in the source bucket.")
                  return

              for obj in response['Contents']:
                  backup_key = f"{timestamp}/{obj['Key']}"
                  copy_source = {'Bucket': source_bucket, 'Key': obj['Key']}
                  s3.copy_object(CopySource=copy_source, Bucket=backup_bucket, Key=backup_key)
                  print(f"Backup created for {obj['Key']} as {backup_key}")

              return {
                  'statusCode': 200,
                  'body': json.dumps('Backup completed successfully!')
              }
      Environment:
        SOURCE_BUCKET: !Ref SourceBucket
        BACKUP_BUCKET: !Ref BackupBucket
      Role: !GetAtt LambdaExecutionRole.Arn

  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaS3Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub arn:aws:s3:::${SourceBucket}/*
                  - !Sub arn:aws:s3:::${BackupBucket}/*